### ISSUE TITLE
Datepicker inside a modal window causes modal to close

### ISSUE THREAD

**Issue by gromon42** [katemihalikova/ion-datetime-picker#55]
Hey, 

I have an issue in my app, i have 2 inputs in which i'm getting the values of your datepickers but when i pick a date too quickly and then try to click on the other input field then it causes my current modal to close itself. 

I've checked online for a quick fix but nothing seems to match my current problem. Maybe adding some setTimeOut on the Ok button validation will fix the problem but that is not the best way to handle things in my opinion.

Looking forward to hear if you got the same problem at some point

**Comment by katemihalikova** [comment]
Hi Gaultier,
could you please make up a codepen/plnkr/jsbin demonstrating your problem? Thanks!

**Comment by neolectron** [comment]
Here's the problem.
I know its not only about your dateTimePicker but its the same bug.
So it directly affect your work.
http://codepen.io/anon/pen/KrxRXx

--- instruction :
open a modal -> open an alert/popup -> close and QUICKLY click anywhere on the modal.
It will cause the modal to close itself too.

**Comment by gromon42** [comment]
Yes that is exactly the bug that i'm having actually ! I ve also just seen your latest issue posted on the ionic framework and it doesnt seem to have a fix for it just yet. But yeah it would be nice if we could find a solution all together because this is happening with all popups/alert/confirm.

**Comment by katemihalikova** [comment]
Thanks! 

The bug lays in ionic. AFAIK their backdrops are separate entities and clicking on a backdrop closes the topmost entity. When the popup is being hidden, the backdrop already knows that the topmost entity is now the modal, but the backdrop is still clickable until its animation ends. When the backdrop is clicked in such situation, the modal is closed, because backdrop service doesn't know that the backdrop is being hidden and shouldn't be clickable. 

You can watch and :+1: driftyco/ionic#5869 issue that should solve that. Workaround for now is to set `backdropClickToClose: false` in modal options object. 

I'm going to close this issue as the problem lays in framework code and workaround exists.

**Comment by Cameron637** [comment]
@katemihalikova  is there any other workaround? setting `enableBackdropDismiss: false` (this is the new version of `backdropClickToClose`) did not work for me.  I even set `showBackdrop: false` and the modal still gets dismissed.

**Comment by katemihalikova** [comment]
Ionic 1.3.1 still uses `backdropClickToClose`. Ionic 2 is not supported by this plugin, but I can look into it if you are able to prepare a codepen/plnkr/jsbin/whatever with the problem.
